onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - workerd
